# Generated by Django 5.0.1 on 2024-01-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image",),
    ]
